### PR TITLE
#7 Support for hexagonal maps

### PR DESCRIPTION
**Pull request by Tubeliar**
This commit supports both flat top and pointy top hexagons, as well as even and odd staggering. Both tile size and hex side length are taken into account to determine Godot's equivalent cell size.

### CODE REVIEW

**Comment by vnen** [comment]
That's awesome, thanks!

The email you used to commit is not tied to your GitHub account. It's not a problem per se but it won't be shown in your profile. You can either amend the commit to change the authorship or add the email you used to the GitHub account.

In any case, I would like you to [amend the commit](http://docs.godotengine.org/en/3.0/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) to change the message to something like:

```
Add support for hexagonal maps

Closes #7
```

This way it's clearer when reading the log and it'll automatically close the issue when the PR is merged.

**Comment by Tubeliar** [comment]
Done! It created a merge within the branch, but i hope that's not a problem.

**Comment by vnen** [comment]
Sorry for the delay. I do prefer you can rebase to a single commit. Otherwise I'll do it myself later on.

**Comment by Tubeliar** [comment]
It should be all right now :-)

**Pull request merged**
