### PR TITLE
add support for tscn scene format

### PR DESCRIPTION
**Pull request by TeddyDD**
It works for me :) Next step would be to save tilesets as tres. I will dig into this later.

### CODE REVIEW

**Comment by vnen** [comment]
AFAIK `.tscn` does not support the metadata, so the reimport wouldn't work. Can you test if it happens?

**Comment by TeddyDD** [comment]
Sorry for delay, my laptop was broken. I'll test it as soon as possible

**Comment by TeddyDD** [comment]
@vnen Yep, you are right, I can't see any metadata in tscn. What do you mean by reimport?

**Comment by vnen** [comment]
If you change the original Tiled file, Godot will automatically reimport the map. Also, if you right-click on the generated scene in the FileSystem dock there's a reimport option which will open the import dialog again with all the options filled according to the metadata.

**Comment by TeddyDD** [comment]
Oh I see. I'll try to dig into it. Maybe I could try to store metadata in some auxiliary node in tscn scenes

**Comment by vnen** [comment]
I'm still not convinced by the usefulness of this. You can't really edit the imported scene because Godot reimports it when the source Tiled map changed, which will make you lose your changes. Of course, reimport does not work with .tscn, so technically you *could* edited that scene without fear but it would mean never been able to reimport the map again without losing the changes.

IMO the best workflow (as intended by Godot's import system) is leave the .scn as is and make an inherited scene or instance it elsewhere to make the changes there. It avoids the problem because reimporting will change your scene but won't override your changes. This new scene can be saved as .tscn if you want.

**Comment by TeddyDD** [comment]
Yeah you probably right. I'll close this PR, at least for now :)

**Pull request closed without merging**
